"""
Core particle simulator module based on superstring excitations, compactifications, and projections.
Models GSO projections, effective 4D particle generation, and Calabi-Yau particle spectra.
"""

import math
from typing import Dict, Any, Union, Optional
from pydantic import BaseModel, Field


class ParticleState(BaseModel):
    """Represents a physical particle state generated by a superstring mode."""
    name: str = Field(..., description="Particle name (e.g., Graviton, Photon, Up Quark)")
    mass_squared: float = Field(..., description="Effective 4D mass squared in GeV^2")
    mass: Union[float, complex] = Field(..., description="Effective 4D physical mass (real or complex/imaginary)")
    spin: float = Field(..., description="Spin of the particle (0, 0.5, 1, 1.5, 2)")
    is_tachyon: bool = Field(..., description="True if mass squared is negative (tachyonic instability)")
    is_gso_allowed: bool = Field(..., description="True if the state survives the GSO projection")
    gauge_representation: str = Field(..., description="Gauge group representation in 4D (e.g., 27 of E6)")
    description: str = Field(..., description="Physical details and description of the state")


class StringParticleSimulator:
    """Computational physics simulator to assemble particles from 10D/11D string configurations."""
    
    def __init__(self, alpha_prime: float = 1.0, g_s: float = 0.1):
        self.alpha_prime = alpha_prime
        self.g_s = g_s
        self.string_mass = 1.0 / math.sqrt(self.alpha_prime)

    def check_gso_projection(self, sector: str, N: float) -> bool:
        """
        Applies GSO (Gliozzi-Scherk-Olive) projection criteria to check state physical validity.
        
        NS Sector: Only half-integer excitations (N = 0.5, 1.5, 2.5...) survive,
                  which projects out the unstable N=0 tachyon.
        R Sector: Only integer excitations (N = 0, 1, 2...) survive.
        """
        sec = sector.upper()
        if sec == "NS" or sec.startswith("NS-NS"):
            # Check if N is an odd multiple of 0.5 (half-integer)
            # mathematically: N = k + 0.5 where k is an integer
            return math.isclose(N % 1.0, 0.5, abs_tol=1e-9)
        elif sec == "R" or sec.startswith("R-R"):
            # Check if N is an integer
            return math.isclose(N % 1.0, 0.0, abs_tol=1e-9)
        elif "-" in sec:
            # For mixed sectors (NS-R / R-NS), it must satisfy level-matching first
            # and left/right must independently satisfy GSO.
            parts = sec.split("-")
            # Usually treated as left-mover GSO and right-mover GSO
            return True # Assumed valid under individual sector checks
        return True

    def assemble_particle(
        self,
        theory_name: str,
        sector: str,
        N_L: float,
        N_R: float,
        n: int = 0,
        w: int = 0,
        R: float = 1.0,
        susy_breaking_scale: float = 0.0
    ) -> ParticleState:
        """
        Assembles a 4D particle from string vibrations, compactifications, and SUSY breaking.
        
        M_4D^2 = M_vib^2 + M_KK^2 + M_winding^2 + M_susy_break^2
        """
        theory_key = theory_name.replace(" ", "_")
        is_closed = "open" not in sector.lower() and theory_key != "Type_I"
        
        # 1. Base Vibrational Mass
        a_L = 0.5 if "NS" in sector.upper().split("-")[0] else 0.0
        a_R = 0.5 if "NS" in sector.upper().split("-")[-1] else 0.0
        
        # GSO checks
        gso_l = self.check_gso_projection("NS" if a_L == 0.5 else "R", N_L)
        gso_r = self.check_gso_projection("NS" if a_R == 0.5 else "R", N_R)
        is_gso_allowed = gso_l and gso_r
        
        if is_closed:
            # Closed string: M^2 = 4/alpha' * (N_L - a_L) under level matching
            left_eff = N_L - a_L
            mass_sq_vib = (4.0 / self.alpha_prime) * left_eff
        else:
            # Open string: M^2 = 1/alpha' * (N_L - a_L)
            left_eff = N_L - a_L
            mass_sq_vib = (1.0 / self.alpha_prime) * left_eff

        # 2. Compactification Mass contributions
        kk_contrib = (n / R) ** 2 if R > 0 else 0.0
        winding_contrib = (w * R / self.alpha_prime) ** 2 if R > 0 else 0.0
        
        # 3. Supersymmetry breaking contribution (gives small positive shift to fermions)
        # e.g., to model electron mass from massless string ground states
        susy_contrib = susy_breaking_scale ** 2
        
        # Total mass squared
        mass_sq_total = mass_sq_vib + kk_contrib + winding_contrib + susy_contrib
        
        is_tachyon = mass_sq_total < 0
        if is_tachyon:
            mass = complex(0.0, math.sqrt(abs(mass_sq_total)))
        else:
            mass = math.sqrt(mass_sq_total)
            
        # Determine Spin, Gauge Representation and Name based on sectors
        spin = 1.0
        gauge_rep = "Adjoint Representation"
        name = "Excited String State"
        description = "A massive string resonance."

        # Identifications of low energy states
        if math.isclose(mass_sq_vib, 0.0, abs_tol=1e-9) and n == 0 and w == 0:
            if is_closed:
                if "NS-NS" in sector.upper() or (a_L == 0.5 and a_R == 0.5):
                    if math.isclose(N_L, 0.5) and math.isclose(N_R, 0.5):
                        name = "Graviton"
                        spin = 2.0
                        gauge_rep = "Singlet (Gravity)"
                        description = "Massless spin-2 mediator of spacetime curvature."
                elif "R-R" in sector.upper() or (a_L == 0.0 and a_R == 0.0):
                    name = "RR Form Field State"
                    spin = 1.0
                    gauge_rep = "Singlet"
                    description = "Ramond-Ramond massless form field quantum."
            else:
                if a_L == 0.5: # NS open string massless vector
                    name = "Gauge Boson"
                    spin = 1.0
                    gauge_rep = "Adjoint of SO(32)"
                    description = "Massless spin-1 Yang-Mills gauge vector boson."
                elif a_L == 0.0: # R open string massless fermion
                    name = "Gaugino"
                    spin = 0.5
                    gauge_rep = "Adjoint of SO(32)"
                    description = "Massless spin-1/2 gaugino supersymmetric partner."

        if is_tachyon:
            name = "Tachyon"
            spin = 0.0
            gauge_rep = "Unstable Singlet"
            description = "Unphysical tachyonic state indicating vacuum instability."

        return ParticleState(
            name=name,
            mass_squared=mass_sq_total,
            mass=mass,
            spin=spin,
            is_tachyon=is_tachyon,
            is_gso_allowed=is_gso_allowed,
            gauge_representation=gauge_rep,
            description=description
        )

    def get_e6_representations(self, h_11: int, h_21: int) -> Dict[str, Any]:
        """
        Calculates E6 Grand Unified Theory (GUT) decomposition spectrum under Calabi-Yau 3-fold.
        
        The standard model particles are nested within the 27 and 27-bar representations of E6.
        """
        chi = 2 * (h_11 - h_21)
        generations = abs(chi) // 2
        
        # 27 representation contains: Q(6), u^c(3), d^c(3), L(2), e^c(1), plus extras (exotic D-quarks, leptons, singlet)
        # Totaling 27 chiral fields per generation!
        total_chiral_fields = generations * 27
        
        return {
            "h_11": h_11,
            "h_21": h_21,
            "euler_characteristic": chi,
            "net_generations": generations,
            "chiral_multiplets_27": h_21,
            "chiral_multiplets_27_bar": h_11,
            "total_chiral_fields_4d": total_chiral_fields,
            "gauge_breaking_path": [
                "E8 x E8 (10D Heterotic Gauge Group)",
                "➔ E6 x SU(3)_holonomy (Spin connection embedded on Calabi-Yau)",
                "➔ SO(10) x U(1)_ψ (Grand Unified Theory breaking)",
                "➔ SU(5) x U(1)_χ (Minimal GUT scheme)",
                "➔ SU(3)_C x SU(2)_L x U(1)_Y (Standard Model Gauge Group)"
            ]
        }
